/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Tiempos Headline"', '"Cormorant Garamond"', '"EB Garamond"', 'Garamond', '"Times New Roman"', 'serif'],
        body: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        code: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        canvas: '#faf9f5',
        background: '#faf9f5',
        'surface-soft': '#f5f0e8',
        'surface-card': '#efe9de',
        'surface-cream-strong': '#e8e0d2',
        'surface-dark': '#181715',
        'surface-dark-elevated': '#252320',
        'surface-dark-soft': '#1f1e1b',
        surface: '#efe9de',
        hairline: '#e6dfd8',
        'hairline-soft': '#ebe6df',
        border: '#e6dfd8',
        ink: '#141413',
        body: '#3d3d3a',
        'body-strong': '#252523',
        muted: '#6c6a64',
        'muted-soft': '#8e8b82',
        'text-primary': '#141413',
        'text-secondary': '#6c6a64',
        'on-primary': '#ffffff',
        'on-dark': '#faf9f5',
        'on-dark-soft': '#a09d96',
        primary: {
          DEFAULT: '#cc785c',
          active: '#a9583e',
          disabled: '#e6dfd8',
        },
        accent: {
          DEFAULT: '#cc785c',
          hover: '#a9583e',
          pressed: '#8f4731',
          subtle: 'rgba(204, 120, 92, 0.14)',
          ring: 'rgba(204, 120, 92, 0.28)',
          teal: '#5db8a6',
          amber: '#e8a55a',
        },
        success: '#5db872',
        warning: '#d4a017',
        error: '#c64545',
        'user-bubble': '#f5e7de',
        'assistant-bubble': '#faf9f5',
        'tool-bubble': '#1f1e1b',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        panel: '12px',
        bubble: '12px',
      },
      boxShadow: {
        soft: '0 1px 3px rgba(20, 20, 19, 0.08)',
        'product-inner': 'inset 0 1px 0 rgba(250, 249, 245, 0.08)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [],
};
